### ISSUE TITLE
extrapolate problem

### ISSUE THREAD

**Issue by Promoto** [ttk592/spline#5]
Hi ! it is so easy to use. Thanks
Can you change the extrapolation like alglib , it will really help me a lot .

**Comment by ttk592** [comment]
Extrapolation is by design at most quadratic and linear for natural boundary conditions. I guess ALGLIB probably extrapolates using the same coefficients as the first and last spline interval. Difference to this implementation is that here we drop the cubic coefficients for extrapolation. You could simply modify the source yourself. Look in `double spline::operator()` and remove the case `if(x<m_x[0])` and look in the code where `m_d[n-1] = 0.0` is set and remove that as well.
